import type { Card } from './types';

// Sample card library shaped around an Iyslander Wizard/Ice deck. Replace
// with the backend catalog once it's available; until then this is enough to
// populate every screen the prototype shows.

export const CARDS: readonly Card[] = [
  {
    id: 'blazing-aether-r',
    key: 'blazing-aether',
    name: 'Blazing Aether',
    pitch: 1,
    cost: 0,
    type: 'Wizard Action',
    subtype: 'Non-Attack',
    power: null,
    defense: 2,
    talent: 'Elemental',
    go: false,
  },
  {
    id: 'blazing-aether-y',
    key: 'blazing-aether',
    name: 'Blazing Aether',
    pitch: 2,
    cost: 0,
    type: 'Wizard Action',
    subtype: 'Non-Attack',
    power: null,
    defense: 2,
    talent: 'Elemental',
    go: false,
  },
  {
    id: 'blazing-aether-b',
    key: 'blazing-aether',
    name: 'Blazing Aether',
    pitch: 3,
    cost: 0,
    type: 'Wizard Action',
    subtype: 'Non-Attack',
    power: null,
    defense: 2,
    talent: 'Elemental',
    go: false,
  },
  {
    id: 'channel-lake-frigid-r',
    key: 'channel-lake-frigid',
    name: 'Channel Lake Frigid',
    pitch: 1,
    cost: 0,
    type: 'Wizard Action',
    subtype: 'Aura',
    power: null,
    defense: 2,
    talent: 'Ice',
    go: false,
  },
  {
    id: 'channel-lake-frigid-y',
    key: 'channel-lake-frigid',
    name: 'Channel Lake Frigid',
    pitch: 2,
    cost: 0,
    type: 'Wizard Action',
    subtype: 'Aura',
    power: null,
    defense: 2,
    talent: 'Ice',
    go: false,
  },
  {
    id: 'frostbite-y',
    key: 'frostbite',
    name: 'Frostbite',
    pitch: 2,
    cost: 1,
    type: 'Wizard Action',
    subtype: 'Aura · Non-Attack',
    power: null,
    defense: 2,
    talent: 'Ice',
    go: false,
  },
  {
    id: 'frost-hex-b',
    key: 'frost-hex',
    name: 'Frost Hex',
    pitch: 3,
    cost: 0,
    type: 'Wizard Action',
    subtype: 'Aura',
    power: null,
    defense: 3,
    talent: 'Ice',
    go: false,
  },
  {
    id: 'waning-moon-r',
    key: 'waning-moon',
    name: 'Waning Moon',
    pitch: 1,
    cost: 1,
    type: 'Wizard Attack',
    subtype: 'Arcane',
    power: 4,
    defense: 3,
    talent: 'Ice',
    go: true,
  },
  {
    id: 'sigil-of-solace-r',
    key: 'sigil-of-solace',
    name: 'Sigil of Solace',
    pitch: 1,
    cost: 0,
    type: 'Wizard Action',
    subtype: 'Non-Attack',
    power: null,
    defense: 3,
    talent: null,
    go: false,
  },
  {
    id: 'sigil-of-solace-y',
    key: 'sigil-of-solace',
    name: 'Sigil of Solace',
    pitch: 2,
    cost: 0,
    type: 'Wizard Action',
    subtype: 'Non-Attack',
    power: null,
    defense: 3,
    talent: null,
    go: false,
  },
  {
    id: 'snapdragon-scalers-y',
    key: 'snapdragon',
    name: 'Snapdragon Scalers',
    pitch: 2,
    cost: 0,
    type: 'Equipment',
    subtype: 'Legs',
    power: null,
    defense: 1,
    talent: null,
    go: false,
  },
  {
    id: 'frostbite-headwear-r',
    key: 'glacial-crown',
    name: 'Crown of Glacial Insight',
    pitch: 1,
    cost: 1,
    type: 'Equipment',
    subtype: 'Head',
    power: null,
    defense: 1,
    talent: 'Ice',
    go: false,
  },
  {
    id: 'rime-blade-b',
    key: 'rime-blade',
    name: 'Rime Blade',
    pitch: 3,
    cost: 0,
    type: 'Equipment',
    subtype: 'Off-Hand · Weapon',
    power: 1,
    defense: 0,
    talent: 'Ice',
    go: false,
  },
  {
    id: 'aether-icevein-b',
    key: 'aether-icevein',
    name: 'Aether Icevein',
    pitch: 3,
    cost: 0,
    type: 'Equipment',
    subtype: 'Arms',
    power: null,
    defense: 1,
    talent: 'Ice',
    go: false,
  },
  {
    id: 'icy-encounter-r',
    key: 'icy-encounter',
    name: 'Icy Encounter',
    pitch: 1,
    cost: 0,
    type: 'Wizard Attack',
    subtype: 'Arcane',
    power: 5,
    defense: 3,
    talent: 'Ice',
    go: false,
  },
  {
    id: 'icy-encounter-y',
    key: 'icy-encounter',
    name: 'Icy Encounter',
    pitch: 2,
    cost: 0,
    type: 'Wizard Attack',
    subtype: 'Arcane',
    power: 5,
    defense: 3,
    talent: 'Ice',
    go: false,
  },
  {
    id: 'voltaire-strikes-r',
    key: 'voltaire',
    name: 'Voltaire Strikes',
    pitch: 1,
    cost: 1,
    type: 'Wizard Attack',
    subtype: 'Lightning',
    power: 5,
    defense: 3,
    talent: 'Lightning',
    go: false,
  },
  {
    id: 'tome-of-aetherwind-y',
    key: 'tome',
    name: 'Tome of Aetherwind',
    pitch: 2,
    cost: 0,
    type: 'Wizard Action',
    subtype: 'Non-Attack',
    power: null,
    defense: 2,
    talent: 'Elemental',
    go: true,
  },
  {
    id: 'channel-mount-heroic-b',
    key: 'channel-mtn',
    name: 'Channel Mount Heroic',
    pitch: 3,
    cost: 0,
    type: 'Wizard Action',
    subtype: 'Aura',
    power: null,
    defense: 3,
    talent: 'Earth',
    go: false,
  },
];

export function findCard(id: string): Card | null {
  return CARDS.find((c) => c.id === id) ?? null;
}

export function requireCard(id: string): Card {
  const card = findCard(id);
  if (!card) {
    throw new Error(`Card fixture not found: ${id}`);
  }
  return card;
}
