/**
 * Generated by scripts/generate-api.mjs from openapi.json @ c8f8b3a826ad9c99a505ff4780c44560313aabad.
 * Source: https://raw.githubusercontent.com/chainsmith-deck-builder/chainsmith/c8f8b3a826ad9c99a505ff4780c44560313aabad/openapi.json
 * Do not edit by hand — re-run `pnpm api:generate` to refresh.
 */

export interface paths {
    "/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDecks"];
        put?: never;
        post: operations["createDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeck"];
        put?: never;
        post?: never;
        delete: operations["deleteDeck"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/heroes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHeroes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Card: {
            classes: components["schemas"]["Class"][];
            /** Format: int32 */
            cost?: number | null;
            /** Format: int32 */
            defense?: number | null;
            flavorText?: string | null;
            functionalText?: string | null;
            hero?: null | components["schemas"]["HeroFacts"];
            id: components["schemas"]["CardId"];
            keywords: components["schemas"]["Keyword"][];
            legalitySummary: components["schemas"]["LegalitySummary"];
            name: string;
            /** Format: int32 */
            pitch?: number | null;
            /** Format: int32 */
            power?: number | null;
            specializations: components["schemas"]["HeroMoniker"][];
            subtypes: string[];
            talents: components["schemas"]["Talent"][];
            typeText?: string | null;
            types: components["schemas"]["CardType"][];
            weaponGrip?: null | components["schemas"]["WeaponGrip"];
        };
        CardDetail: {
            card: components["schemas"]["Card"];
            printings: components["schemas"]["Printing"][];
        };
        CardId: string;
        CardListResponse: {
            items: components["schemas"]["CardSummary"][];
            /**
             * @description Opaque cursor; pass back as `cursor` to fetch the next page. `null`
             *     when there are no more results.
             */
            nextCursor?: string | null;
        };
        CardSummary: {
            classes: components["schemas"]["Class"][];
            /** Format: int32 */
            cost?: number | null;
            defaultPrinting?: null | components["schemas"]["PrintingSummary"];
            /** Format: int32 */
            defense?: number | null;
            id: components["schemas"]["CardId"];
            legalitySummary: components["schemas"]["LegalitySummary"];
            name: string;
            /** Format: int32 */
            pitch?: number | null;
            /** Format: int32 */
            power?: number | null;
            talents: components["schemas"]["Talent"][];
            types: components["schemas"]["CardType"][];
        };
        /** @enum {string} */
        CardType: "hero" | "action" | "attack_action" | "attack_reaction" | "defense_reaction" | "instant" | "equipment" | "weapon" | "mentor" | "resource" | "token";
        /** @enum {string} */
        Class: "assassin" | "bard" | "brute" | "guardian" | "illusionist" | "mechanologist" | "merchant" | "ninja" | "ranger" | "runeblade" | "shapeshifter" | "warrior" | "wizard";
        CreateDeckRequest: {
            /** @description The pool/hero/format/loadouts to save. */
            deck: components["schemas"]["Deck"];
            description?: string | null;
            /** @description Display name shown to the user (and to other users for public decks). */
            name: string;
            tags?: string[];
            visibility?: null | components["schemas"]["Visibility"];
        };
        Deck: {
            format: components["schemas"]["FormatId"];
            hero: components["schemas"]["PrintingId"];
            loadouts: components["schemas"]["Loadout"][];
            pool: components["schemas"]["PoolEntry"][];
        };
        DeckListResponse: {
            items: components["schemas"]["DeckSummary"][];
        };
        DeckResponse: {
            /** Format: date-time */
            createdAt: string;
            deck: components["schemas"]["Deck"];
            description?: string | null;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            ownerId: string;
            tags: string[];
            /** Format: date-time */
            updatedAt: string;
            visibility: components["schemas"]["Visibility"];
        };
        DeckSummary: {
            /** Format: date-time */
            createdAt: string;
            format: components["schemas"]["FormatId"];
            hero: components["schemas"]["PrintingId"];
            /** Format: uuid */
            id: string;
            name: string;
            tags: string[];
            /** Format: date-time */
            updatedAt: string;
            visibility: components["schemas"]["Visibility"];
        };
        /** @enum {string} */
        Edition: "alpha" | "unlimited" | "first";
        EquipmentLoadout: {
            arms?: null | components["schemas"]["PrintingId"];
            chest?: null | components["schemas"]["PrintingId"];
            head?: null | components["schemas"]["PrintingId"];
            legs?: null | components["schemas"]["PrintingId"];
            mainHand?: null | components["schemas"]["PrintingId"];
            offHand?: null | components["schemas"]["PrintingId"];
        };
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * @description Stable, machine-readable error codes. Clients are allowed to switch on
         *     these. Adding a variant is additive; renaming or removing one is a
         *     breaking change in production phase (see `.claude/rules/api-contract.md`).
         * @enum {string}
         */
        ErrorCode: "database_error" | "unsupported_format" | "not_found" | "unauthorized" | "forbidden" | "auth_not_configured";
        ErrorDetail: {
            code: components["schemas"]["ErrorCode"];
            details?: unknown;
            message: string;
        };
        EssenceGrant: {
            /** @enum {string} */
            kind: "class";
            value: components["schemas"]["Class"];
        } | {
            /** @enum {string} */
            kind: "talent";
            value: components["schemas"]["Talent"];
        };
        /** @enum {string} */
        Foiling: "standard" | "rainbow_foil" | "cold_foil" | "gold_foil";
        /** @enum {string} */
        FormatId: "classic_constructed" | "blitz" | "commoner" | "silver_age" | "living_legend" | "ultimate_pit_fight";
        /** @enum {string} */
        FormatStatus: "legal" | "banned" | "suspended" | "restricted" | "living_legend_retired" | "not_eligible";
        HealthResponse: {
            db: string;
            status: string;
        };
        HeroFacts: {
            /** Format: int32 */
            arcane?: number | null;
            /**
             * @description Class/Talent supertypes the hero grants via "Essence of X" abilities.
             *     These are unioned with the hero's printed supertypes when checking
             *     CR 1.1.3 (supertype subset rule).
             */
            essenceGrants: components["schemas"]["EssenceGrant"][];
            /** Format: int32 */
            intellect?: number | null;
            kind: components["schemas"]["HeroKind"];
            /** Format: int32 */
            life: number;
            /**
             * Format: int32
             * @description Number of weapon zones the hero has — i.e. the maximum number of
             *     `CardType::Weapon` printings the loadout may equip across main and
             *     off-hand combined. Default 2 (the standard hero). Kayo variants
             *     override to 1; Bolfar to 0. Non-weapon equipment in the off-hand slot
             *     (shields, Companion items, etc.) does not consume a weapon zone.
             */
            weaponZoneCount: number;
        };
        /** @enum {string} */
        HeroKind: "adult" | "young" | "pit_fighter";
        HeroListResponse: {
            items: components["schemas"]["HeroSummary"][];
            nextCursor?: string | null;
        };
        /**
         * @description The first comma-separated token of a hero's name (e.g. "Bravo, Star of the
         *     Show" -> "Bravo"). FaB specialization rules match on moniker, not full name.
         */
        HeroMoniker: string;
        HeroSummary: {
            /** Format: int32 */
            arcane?: number | null;
            classes: components["schemas"]["Class"][];
            defaultPrinting?: null | components["schemas"]["PrintingSummary"];
            essenceGrants: components["schemas"]["EssenceGrant"][];
            id: components["schemas"]["CardId"];
            /** Format: int32 */
            intellect?: number | null;
            kind: components["schemas"]["HeroKind"];
            legalitySummary: components["schemas"]["LegalitySummary"];
            /** Format: int32 */
            life: number;
            name: string;
            talents: components["schemas"]["Talent"][];
        };
        /**
         * @description Free-form keyword. Upstream prints new keywords every set, so an enum here
         *     would be brittle and is not needed for legality checks (the validator does
         *     not switch on keyword).
         */
        Keyword: string;
        /**
         * @description Snapshot of per-format legality from the upstream `card.json` flat booleans.
         *     Convenience for catalog filtering only — the validator is the source of
         *     truth for legality at a specific date.
         */
        LegalitySummary: {
            blitz: components["schemas"]["FormatStatus"];
            cc: components["schemas"]["FormatStatus"];
            commoner: components["schemas"]["FormatStatus"];
            livingLegend: components["schemas"]["FormatStatus"];
            silverAge: components["schemas"]["FormatStatus"];
            upf: components["schemas"]["FormatStatus"];
        };
        Loadout: {
            deckCards: components["schemas"]["LoadoutEntry"][];
            equipment: components["schemas"]["EquipmentLoadout"];
            name: string;
        };
        LoadoutEntry: {
            printing: components["schemas"]["PrintingId"];
            /** Format: int32 */
            quantity: number;
        };
        PoolEntry: {
            printing: components["schemas"]["PrintingId"];
            /** Format: int32 */
            quantity: number;
        };
        Printing: {
            artist?: string | null;
            cardId: components["schemas"]["CardId"];
            collectorNumber: string;
            edition: components["schemas"]["Edition"];
            foiling: components["schemas"]["Foiling"];
            id: components["schemas"]["PrintingId"];
            /**
             * @description CDN URL for the card image, sourced from upstream. Clients (web,
             *     iOS, Android) load this URL directly from the LSS CDN — we do not
             *     proxy or cache imagery on our infrastructure (see
             *     `.claude/rules/security.md`).
             */
            imageUrl?: string | null;
            rarity: components["schemas"]["Rarity"];
            set: components["schemas"]["SetCode"];
            /** Format: date */
            setReleaseDate: string;
            treatment: components["schemas"]["Treatment"];
        };
        PrintingId: string;
        PrintingSummary: {
            id: components["schemas"]["PrintingId"];
            imageUrl?: string | null;
            rarity: components["schemas"]["Rarity"];
            set: components["schemas"]["SetCode"];
        };
        /** @enum {string} */
        Rarity: "common" | "rare" | "super_rare" | "majestic" | "legendary" | "fabled" | "promo" | "token";
        SetCode: string;
        /** @enum {string} */
        Talent: "draconic" | "earth" | "elemental" | "ice" | "light" | "lightning" | "shadow" | "wind";
        /** @enum {string} */
        Treatment: "standard" | "extended_art" | "marvel" | "alternate_art";
        ValidateRequest: {
            /**
             * Format: date
             * @description Validation date. Used to evaluate time-evolving rules (banned list,
             *     Living Legend retirement). Defaults to today UTC if omitted.
             */
            date?: string | null;
            deck: components["schemas"]["Deck"];
        };
        ValidationResponse: {
            /** Format: date */
            date: string;
            format: components["schemas"]["FormatId"];
            /** @description True iff `violations` is empty. */
            valid: boolean;
            violations: components["schemas"]["Violation"][];
        };
        Violation: {
            code: components["schemas"]["ViolationCode"];
            details?: null | components["schemas"]["ViolationDetails"];
            message: string;
        };
        /**
         * @description Stable codes clients are allowed to switch on.
         *
         *     Adding a variant is additive. Renaming or removing one is a breaking
         *     change in the production phase (see `.claude/rules/api-contract.md`).
         * @enum {string}
         */
        ViolationCode: "hero_printing_not_found_in_catalog" | "hero_not_eligible_for_format" | "hero_living_legend_retired" | "hero_missing_hero_type" | "pool_size_above_max" | "deck_size_below_min" | "deck_size_above_max" | "copy_limit_exceeded" | "restricted_copy_limit_exceeded" | "card_not_found_in_catalog" | "printing_not_found_in_catalog" | "card_not_eligible_for_format" | "card_banned" | "supertype_mismatch" | "specialization_mismatch" | "loadout_printing_not_in_pool" | "loadout_quantity_exceeds_pool" | "equipment_slot_wrong" | "equipment_not_in_pool" | "weapon_config_invalid";
        ViolationDetails: {
            card_id: components["schemas"]["CardId"];
            /** @enum {string} */
            kind: "card";
            name: string;
        } | {
            /** @enum {string} */
            kind: "printing";
            printing_id: components["schemas"]["PrintingId"];
        } | {
            /** Format: int32 */
            allowed: number;
            card_id: components["schemas"]["CardId"];
            /** Format: int32 */
            found: number;
            /** @enum {string} */
            kind: "quantity";
        } | {
            /** Format: int32 */
            found: number;
            /** @enum {string} */
            kind: "deck_size";
            /** Format: int32 */
            max?: number | null;
            /** Format: int32 */
            min: number;
        } | {
            /** Format: int32 */
            found: number;
            /** @enum {string} */
            kind: "pool_size";
            /** Format: int32 */
            max: number;
        } | {
            actual_slot?: string | null;
            expected_slot: string;
            /** @enum {string} */
            kind: "equipment_slot";
            printing_id: components["schemas"]["PrintingId"];
        } | {
            /** @enum {string} */
            kind: "loadout_card";
            loadout: string;
            printing_id: components["schemas"]["PrintingId"];
        };
        /** @enum {string} */
        Visibility: "private" | "unlisted" | "public";
        /** @enum {string} */
        WeaponGrip: "one_handed" | "two_handed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCards: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on `name`. */
                text?: string;
                /**
                 * @description Comma-separated list of class names. A card matches if it has any
                 *     listed class. Generic cards (no class) match only when the filter is
                 *     omitted.
                 */
                classes?: string;
                /**
                 * @description Comma-separated list of talent names. A card matches if it has any
                 *     listed talent.
                 */
                talents?: string;
                /**
                 * @description Comma-separated list of card type names. A card matches if it has
                 *     any listed type.
                 */
                types?: string;
                pitch?: number;
                costMin?: number;
                costMax?: number;
                /**
                 * @description Filter to cards that are currently `Legal` or `Restricted` in the
                 *     given format (snapshot-based, not date-aware — for date-aware
                 *     validation use `POST /validate`).
                 */
                format?: components["schemas"]["FormatId"];
                /**
                 * @description Card id of a hero. Restricts results to cards whose supertypes are a
                 *     subset of the hero's effective supertypes (CR 1.1.3).
                 */
                legalForHero?: components["schemas"]["CardId"];
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cards matching the filter, paginated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListResponse"];
                };
            };
            /** @description Malformed query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card unique id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card with all printings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listDecks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decks owned by the authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckListResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    createDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeckRequest"];
            };
        };
        responses: {
            /** @description Deck created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckResponse"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deck id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full deck */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckResponse"];
                };
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Deck not found or not visible to caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    deleteDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deck id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (soft) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid Authorization header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Deck not found or not owned by caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service is unhealthy */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listHeroes: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on `name`. */
                text?: string;
                /** @description Comma-separated class names (any-match). */
                classes?: string;
                /** @description Comma-separated talent names (any-match). */
                talents?: string;
                /**
                 * @description `adult`, `young`, or `pit_fighter`. Multiple values not supported —
                 *     most queries want exactly one.
                 */
                kind?: components["schemas"]["HeroKind"];
                /**
                 * @description Filter to heroes currently `Legal` in the given format. CC-legal
                 *     heroes that have been retired to Living Legend will *not* match
                 *     `format=classic_constructed` (their `cc` legality is
                 *     `living_legend_retired`); they will match `format=living_legend`.
                 */
                format?: components["schemas"]["FormatId"];
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Heroes matching the filter, paginated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeroListResponse"];
                };
            };
            /** @description Malformed query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    validateDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Validation completed; check `valid` and `violations` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Malformed request or unsupported format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}

