// Generates src/api/schema.d.ts from the chainsmith backend's openapi.json
// at the SHA pinned in .api-version.
//
// Resolution order:
//   1. https://raw.githubusercontent.com/chainsmith-deck-builder/chainsmith/<SHA>/openapi.json
//   2. ../chainsmith/openapi.json (sibling checkout, dev-only fallback)

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const apiVersionPath = resolve(root, '.api-version');
const outPath = resolve(root, 'src/api/schema.d.ts');

const sha = readFileSync(apiVersionPath, 'utf8').trim();
if (!/^[a-f0-9]{40}$/.test(sha)) {
  console.error(`.api-version: expected a 40-char commit SHA, got ${JSON.stringify(sha)}`);
  process.exit(1);
}

const githubUrl = `https://raw.githubusercontent.com/chainsmith-deck-builder/chainsmith/${sha}/openapi.json`;
const localFallback = resolve(root, '../chainsmith/openapi.json');

let source = githubUrl;
let usedFallback = false;

try {
  const res = await fetch(githubUrl, { method: 'HEAD' });
  if (!res.ok) throw new Error(`HEAD ${githubUrl} returned ${res.status}`);
} catch (err) {
  if (existsSync(localFallback)) {
    console.warn(`network fetch unavailable (${err.message}); falling back to ${localFallback}`);
    source = localFallback;
    usedFallback = true;
  } else {
    console.error(`could not reach ${githubUrl} and no local fallback at ${localFallback}`);
    process.exit(1);
  }
}

const ast = await openapiTS(source);
const contents = astToString(ast);
const banner = [
  '/**',
  ` * Generated by scripts/generate-api.mjs from openapi.json @ ${sha}.`,
  ` * Source: ${usedFallback ? localFallback : githubUrl}`,
  ' * Do not edit by hand — re-run `pnpm api:generate` to refresh.',
  ' */',
  '',
].join('\n');

writeFileSync(outPath, `${banner}\n${contents}\n`);
console.log(`wrote ${outPath}`);
